CREATE TABLE IF NOT EXISTS genders(value_id SMALLINT NOT NULL PRIMARY KEY, property VARCHAR(25) NOT NULL);

-- INSERTS

INSERT INTO genders VALUES(0, 'Gender:');
INSERT INTO genders VALUES(1, 'Male');
INSERT INTO genders VALUES(2, 'Female');
INSERT INTO genders VALUES(4, 'Trans');